Update Docker configuration

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -2,10 +2,15 @@
 
 project_dir=$(cd "$(dirname "$0")" && cd .. && pwd)
 project_name=$(basename "$project_dir")
-architecture=$1
+env=$1
 
-if [ 'arm' == "$architecture" ]; then
-    docker-compose -f ${project_dir}/docker-compose-arm.yml up -d
+if [ ! -f "${project_dir}/.docker-compose.env" ]; then
+    echo "Missing ${project_dir}/.docker-compose.env";
+    exit 1;
+fi
+
+if [ 'prod' == "$env" ]; then
+    docker-compose -f ${project_dir}/docker-compose-prod.yml up -d "${@:2}"
 else
-    docker-compose -f ${project_dir}/docker-compose.yml up -d
+    docker-compose -f ${project_dir}/docker-compose-dev.yml up -d "${@:2}"
 fi
